### ISSUE TITLE
Memory estimator for `normalize` doesn't account for darks/flats space

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomolibgpu#110]
The `normalize` function requires the darks and flats to be in GPU memory in order to calculate their means:
https://github.com/DiamondLightSource/httomolibgpu/blob/2493ac3ab0a70c4e249d9d384f172e08bcdcc8f4/httomolibgpu/prep/normalize.py#L96-L97

The memory estimator for `normalize` takes into account the space needed for:
- the darks mean array
- the flats mean array
- the input and output arrays

but it doesn't take into account the space needed for the darks and flats themselves:
https://github.com/DiamondLightSource/httomolibgpu/blob/2493ac3ab0a70c4e249d9d384f172e08bcdcc8f4/httomolibgpu/prep/normalize.py#L33-L51

Despite the darks/flats not being accounted for in the memory estimation, this does not always result in a CUDA OOM error. There are probably several factors that determine whether or not the lack of darks/flats space in the memory estimation cause GPU memory overflow, such as:
- the size of the input data & the previewed size
- the size of the GPU memory

but perhaps there are more factors that are still unknown.

When processing the 28GB dataset `/dls/k11/data/2023/mg31838-2/nexus/k11-24460.nxs` (no previewing applied) with a P100 that has 16GB of memory, a CUDA OOM error occurs. When processing the same 28GB dataset with no previewing applied with a V100 that has 32GB of memory, no CUDA OOM error occurs.

The P100 16GB case overflows GPU memory because (in chronological order of when they're allocated memory on the GPU):
- the input max slices space (340 slices, ~7GB), transferred in the wrapper class
- the flats array (~800MB), transferred in the wrapper class
- the darks array (~800MB), transferred in the wrapper class
- the darks mean array (~21MB), allocated in the `normalize` function
- the flats mean array (~21MB), allocated in the `normalize` function
- the output space (340 slices, ~7GB), allocated in the `normalize` function

the last one cannot quite fit in GPU memory, due to the darks/flats not being used to calculate the max slices.

If the relevant sized arrays w/ relevant data types are manually allocated in turn on the P100 in a debug session, but skipping the darks/flats, then no CUDA OOM error occurs, which does seem to suggest that the space for the darks/flats that isn't being accounted for in the max slices calculation is the issue.

The reason why the V100 32GB case does not overflow GPU memory is currently unknown (due to being unable to get GPU resources in the cluster), and further investigation is necessary as there may be other factors at play.

**Comment by dkazanc** [comment]
Thanks for spotting this Yousef, it is  a crucial thing that can affect memory calculation, especially for big data or/and small memory GPUs. I [fixed](https://github.com/DiamondLightSource/httomo/blob/5486c4e8453ec4234113c3c5d320b7ca7683ff88/httomo/task_runner.py#L779) it on the httomo side. Making changes to _normalize_max_slices function  would result in changing the way we deal with multiple datasets in the memory estimation. So far this is not the big problem as we only have normalisation that requires multiple datasets for input. Possibly later on we could accommodate this on the httomolibgpu side?
