### ISSUE TITLE
Failing CI (running tests on IRIS)

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomolibgpu#137]
There's a ton of errors in these failing jobs such as [this one](https://github.com/DiamondLightSource/httomolibgpu/actions/runs/9840423817/job/27164627701), but one thing that caught my eye is the following:
```
=============================== warnings summary ===============================
../../../home/runner/micromamba/envs/httomo/lib/python3.11/site-packages/cupy/_environment.py:487
  /home/runner/micromamba/envs/httomo/lib/python3.11/site-packages/cupy/_environment.py:487: UserWarning: 
  --------------------------------------------------------------------------------
  
    CuPy may not function correctly because multiple CuPy packages are installed
    in your environment:
  
      cupy, cupy-cuda11x
  
    Follow these steps to resolve this issue:
  
      1. For all packages listed above, run the following command to remove all
         existing CuPy installations:
  
           $ pip uninstall <package_name>
  
        If you previously installed CuPy via conda, also run the following:
  
           $ conda uninstall cupy
  
      2. Install the appropriate CuPy package.
         Refer to the Installation Guide for detailed instructions.
  
           https://docs.cupy.dev/en/stable/install.html
  
  --------------------------------------------------------------------------------
```

Feels like, if a lot of cupy stuff is misbehaving, this could possibly be the reason? Might be worth trying to see if what it warns about is true (multiple cupy packages installed in the conda env).

**Comment by dkazanc** [comment]
yes, although it ignores: 
`Requirement already satisfied: cupy in /home/runner/micromamba/envs/httomo/lib/python3.11/site-packages (from httomolibgpu==0.0.1) (12.3.0)`
It gets this  `Downloading cupy_cuda11x-13.2.0-cp311-cp311-manylinux2014_x86_64.whl (96.0 MB)`
when running pyproject

**Comment by dkazanc** [comment]
Apparently reverting container image back to `devel`, [fixed](https://github.com/DiamondLightSource/httomolibgpu/commit/83b05bec26de374ffe068ed72db9dcb9b0d559ef) the problem...

**Comment by yousefmoazzam** [comment]
> yes, although it ignores: `Requirement already satisfied: cupy in /home/runner/micromamba/envs/httomo/lib/python3.11/site-packages (from httomolibgpu==0.0.1) (12.3.0)` It gets this `Downloading cupy_cuda11x-13.2.0-cp311-cp311-manylinux2014_x86_64.whl (96.0 MB)` when running pyproject

Without knowing about how `pip` figures out dependencies that are already installed via `conda`, that's kinda weird.

Ah well, this is one of those times where I'm happy to just back away and say "this is fixed" (until we have to deal with it again... :sweat_smile: )
