### ISSUE TITLE
create test data that does not require HTTomo loaders

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomolibgpu#15]
* Keep all I/O for HDF5 in HTTomo and do not use it in httomolib. As a library of methods, lets keep things very simple regarding the data reads. I suggest we create a compressed `npz` file using this [function](https://numpy.org/doc/stable/reference/generated/numpy.savez_compressed.html#numpy.savez_compressed) from hdf5 files.
* Modify unittests accordingly

**Comment by dkazanc** [comment]
@namannimmo10 I will work on this if you don't mind. Cheers

**Comment by namannimmo10** [comment]
Thank you, @dkazanc.  I am happy to "modify unittests accordingly" if you want me to.

**Comment by dkazanc** [comment]
no worries, that's done in #16
