### ISSUE TITLE
Unnecessary copy of Fourier transform of projections in `paganin_filter_tomopy`

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomolibgpu#156]
The 2D IFFT is applied on a filtered version of the projections via `phase_filter * fft_tomo`: https://github.com/DiamondLightSource/httomolibgpu/blob/ce1c15f0a9e09a6fd3070375f473ece421b06685/httomolibgpu/prep/phase.py#L320-L323

However, doing `phase_filter * fft_tomo` creates a copy of the filtered projection data that I think is not necessary.

Instead, what can be done is to apply the filter to the projections with in-place multiplication before the 2D IFFT is applied (we can modify the filtered projections in-place since we don't need to keep ahold of the unfiltered version) and then apply the IFFT like so:
```python
# Filter projections with in-place multiplication
fft_tomo *= phase_filter

# Apply 2D IFFT to filtered projections
ifft_filtered_tomo = (
    ifft2(fft_tomo, axes=(-2, -1), overwrite_x=True)
).real
```

**Comment by dkazanc** [comment]
ah, that's nice. thanks for optimising the code itself. Because of the padding to the power of 2 this function is pretty memory hungry.
