### ISSUE TITLE
Versioning system

### ISSUE THREAD

**Issue by dkazanc** [DiamondLightSource/httomolibgpu#160]
I guess it also applies to other HTTomo packages so we can decide more generally may be @yousefmoazzam ?
When we create a release we trigger the CI job that build this package labelled as `main`.  At midnight, however, we have the auto build that creates a `dev` build using the same tag. So the original `main` release gets [replaced](https://anaconda.org/httomo/httomolibgpu/files)by the `dev` release. 

To fight this problem I usually create 2 `main` releases, the one for the current release and one for the future release which will become the `dev` release at midnight, hence keeping the previous `main` release intact. Then, when I ready to do another release I will delete the tag associated with the `dev` release and re-introduce it again therefore making the `dev` release `main` instead. 

I do appreciate that this might be slightly confusing and it probably should be written somewhere in the repo supporting info. But, in general ,do we agree that this is something we want to do, keep both `dev` and `main` ? Or, just stick to `main` for instance and drop `dev` entirely? I'm not entirely sure that `dev` will be used that much, at least for the libraries.  Then also with PyPy in place we probably be working more with pip installed libraries, so we can keep just one conda main package?

**Comment by yousefmoazzam** [comment]
If I remember correctly, the idea behind the nightly build and uploading to the `dev` label was to be able to test out the latest code in the package from an installation of a conda package, rather than a developer using their local git repo.

If this isn't a common use case for any of the developers (personally, I haven't installed any of the nightly builds of the conda package yet), then it might make sense to stop doing the nightly builds, which would then mean we have no need to upload packages to the `dev` label.

**Comment by dkazanc** [comment]
cheers, I think testing the `dev` package certainly makes sense. This is certainly needed  for more complex and involved software, e.g., `httomo`. I don't think that this is that needed for the libraries as the development itself is quite linear most of the time? It will also probably make our life slightly easier by just releasing the `main` package? 

But if we want to keep doing `dev` releases, then we also need to include the CI job of testing them, otherwise, indeed it is a bit useless.

**Comment by yousefmoazzam** [comment]
For the point about the backend packages like httomolib and httomolibgpu probably not needing `dev`, yeah, I'd agree that uploading packages to the `main` label is enough.

For the point about "testing `dev`", I realise maybe I should have chosen my words more carefully. Before I said this:

> If I remember correctly, the idea behind the nightly build and uploading to the `dev` label was to be able to test out the latest code in the package from an installation of a conda package, rather than a developer using their local git repo.

When I used the word "test", I was meaning that a developer would locally install the nightly build and use it in some way to verify that things were working as expected. I wasn't meaning "test" in the sense of a CI job actually using the nightly build package to do some checking that the code is working as expected.

I'm a bit unsure about the idea of using CI to "test" the packages uploaded to `dev`. The flow of building a package for distribution I commonly see is:
```
run tests in CI -> if they pass, build package + release
```

But with running CI for testing packages uploaded to `dev`, the flow gets more steps and becomes more involved, like:
```
run tests in CI -> if they pass, build package + release -> have a CI job install built package + run tests
```

It feels a bit weird to have to test the code after it's already passed CI and has been built as a package. I do understand that there can be mistakes in packaging that are best caught early, so it may make sense to have CI install a built package and try to test basic things (like that the CLI works or something). But doing any in-depth testing for a package that has already passed tests in CI and been built feels wrong; it feels like any in-depth issues should be caught during the CI tests before the package build occurs.

**Comment by dkazanc** [comment]
I see what you mean, but I guess it comes to then building the conda package on `iris` in order to run tests? We're trying to avoid that as `iris` not being available all the time. I guess when we're building `main` as well we should run tests first. I think let us, for now, remove the `dev` build for libraries?  We can always return it when we actually need it.

**Comment by yousefmoazzam** [comment]
Sure, removing the uploading to the `dev` label for backends sounds reasonable.
