### ISSUE TITLE
Rename `preview` param in `distortion_correction_proj_discorpy()` to be independent of httomo preview concept

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomolibgpu#163]
As the title says, because the method is in a separate repo (and we have purposely introduced this separation between httomo and methods), it would make sense for the `preview` parameter to be named something more generic such that it makes sense in a context outside of httomo.

The preview information from httomo is being used to apply some kind of:
- error checking that the step is 1
- shifting based on the cropping in the det y and det x dimensions
https://github.com/DiamondLightSource/httomolibgpu/blob/74f47dace254a025e9dd41abf2d2937d9b387d8d/httomolibgpu/prep/alignment.py#L91-L110

which hopefully gives some indication for what the new param name could be?

One final note: If it makes sense for the generalisation, maybe it's reasonable to split up the info in the `Dict` into separate parameters?

**Comment by dkazanc** [comment]
thanks, yes this naming of parameters is far from obvious 
```
 shift = preview["starts"] 
 step = preview["steps"] 
```
I suggest we incorporate them as is, two parameters `shift` and `step`?

**Comment by yousefmoazzam** [comment]
Mmm, that seems reasonable. Looking a bit more closely, it seems like we only need the start and step for det y and det x. So the types for both `shift` and `step` could be `Tuple[int, int]`, where the first element is the shift/step for det y, and the second element is the shift/step for det x.

More explicitly:
```python
def distortion_correction_proj_discorpy(
    data: cp.ndarray,
    metadata_path: str,
    shift: Tuple[int, int] = (0, 0),
    step: Tuple[int, int] = (1, 1),
    order: int = 1,
    mode: str = "reflect",
):
```

and the tuples would have the following info:
```python
det_y_shift = shift[0]
det_x_shift = shift[1]
det_y_step = step[0]
det_x_step = step[1]
```

**Comment by dkazanc** [comment]
I've done a bit of rearranging in #161. Few things were slightly confusing, like `stop` value from the `preview` is ignored and `step` is also not going into the method itself.  I also changed the order of values in shifts as `(x,y)`, just to avoid confusion.
