### ISSUE TITLE
`cupy` version constraint is only in conda depedencies, not pip dependencies

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomolibgpu#170]
We've stuck to cupy `12.3.0` for a bit now, due to later versions of cupy dropping support for older cudatoolkit versions, which in turn meant that Pascal architecture nvidia GPUs were not supported in later versions of cupy (the DLS SLURM cluster still has Pascals, so supporting them is of interest).

The conda environment file has this cupy version constraint: https://github.com/DiamondLightSource/httomolibgpu/blob/bc7af7bbf1a10d9aaa8a57f7194ee51e7ebd662e/conda/environment.yml#L6

but the `pyproject.toml` file doesn't:  https://github.com/DiamondLightSource/httomolibgpu/blob/bc7af7bbf1a10d9aaa8a57f7194ee51e7ebd662e/pyproject.toml#L39-L46

This means that httomolibgpu installed from PyPI will have a cupy version that doesn't support Pascals.

**Comment by dkazanc** [comment]
ah, good point. We should bound the cupy version then. We haven't seen the problem just because we have `cupy` already installed in the environment I reckon. I can fix this when I do the new httomolibgpu version soon.
