### ISSUE TITLE
`cupy_run` variable not defined in `cupywrapper.py` if `cupy` is installed but GPU isn't accessible

### ISSUE THREAD

**Issue by yousefmoazzam** [DiamondLightSource/httomolibgpu#173]
(Discovered at the same time as #172, so that's why there's the same information leading up to explaining this issue).

Modules import `cupywrapper` as a means to:
- determine if `cupy` has been installed
- if `cupy` is installed, determine if a GPU is accessible

https://github.com/DiamondLightSource/httomolibgpu/blob/bc7af7bbf1a10d9aaa8a57f7194ee51e7ebd662e/httomolibgpu/cupywrapper.py#L1-L20

In the situation where:
- `cupy` is installed
- but a GPU isn't accessible

then lines 8 to 10 are where control flow goes: https://github.com/DiamondLightSource/httomolibgpu/blob/bc7af7bbf1a10d9aaa8a57f7194ee51e7ebd662e/httomolibgpu/cupywrapper.py#L8-L10

Notice that in this block of code, the variable `cupy_run` isn't defined. So, if `cupy` is installed but the GPU isn't accessible, any module which has attempted to import `cupywrapper.cupy_run`, such as the following: https://github.com/DiamondLightSource/httomolibgpu/blob/bc7af7bbf1a10d9aaa8a57f7194ee51e7ebd662e/httomolibgpu/misc/corr.py#L28-L31

will get a runtime `ImportError`.

It looks like we're trying to handle things such that we default to CPU mode if `cupy` is not installed, or the GPU isn't accessible, so we should probably define `cupy_run = False` in this particular block to avoid a runtime error and let the program continue running in CPU mode.

**Comment by dkazanc** [comment]
thanks for digging into this. Looks like a bug indeed with `cupy_run` is not initialised.
