### ISSUE TITLE
Set up a pre-commit hook

### ISSUE THREAD

**Issue by namannimmo10** [DiamondLightSource/httomolibgpu#57]
Hi team, 
let me know if you are ok with me setting up a pre-commit hook: https://pre-commit.com/
We can add pre-commit plugins to this repo (like trailing whitespace, yaml checker, etc) with `.pre-commit-config.yaml` file.

**Comment by dkazanc** [comment]
totally OK with that, thanks. Would it also suggest changes or just give you a report with issues?
